
[booze_gen]
types = ['Vodka', 'Gin', 'Ovocná', 'Rum', 'Whisky', 'Jiná hnědka']
shops = ['La-vin', 'Top Alkohol', 'Makro', 'Alkohol CZ', 'Fivuza'] 
origins = ['Polsko', 'Rusko', 'Anglie', 'USA', 'Čechy', 'Slovensko', 'Irsko']   
smoothness_levels = ['denaturák','nic moc smooth', 'že trošku pálí', 'celkem smooth', 'smooth jak svině']
